# Generated by Django 2.0.2 on 2018-06-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='steam_apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('appname', models.CharField(max_length=225)),
                ('easyname', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='steam_player_bans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_id', models.CharField(max_length=225)),
                ('steamid', models.CharField(max_length=225)),
                ('communitybanned', models.IntegerField()),
                ('vacbanned', models.IntegerField()),
                ('numberofvacbans', models.IntegerField()),
                ('dayssincelastban', models.IntegerField()),
                ('numberofgamebans', models.IntegerField()),
                ('economyban', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='steam_player_ownedgames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownedgames_id', models.CharField(max_length=225)),
                ('appid', models.IntegerField()),
                ('appname', models.CharField(max_length=225)),
                ('playtime_forever', models.IntegerField()),
                ('img_icon_url', models.CharField(max_length=225)),
                ('img_logo_url', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='steam_player_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_id', models.CharField(max_length=225)),
                ('appid', models.IntegerField()),
                ('name', models.CharField(max_length=225)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='steam_player_summaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_id', models.CharField(max_length=225)),
                ('personname', models.CharField(max_length=225)),
                ('level', models.IntegerField()),
                ('personstate', models.IntegerField()),
                ('lastlogoff', models.DateField()),
                ('profileurl', models.CharField(max_length=225)),
                ('avatar', models.CharField(max_length=225)),
                ('timecreate', models.DateField()),
                ('loccode', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('steamid', models.CharField(max_length=225)),
                ('isAdmin', models.IntegerField(default=0)),
                ('ban_id', models.CharField(max_length=225)),
                ('ownedgames_id', models.CharField(max_length=225)),
                ('stats_id', models.CharField(max_length=225)),
                ('sum_id', models.CharField(max_length=225)),
            ],
        ),
    ]
