# Generated by Django 2.0.2 on 2018-06-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0002_steam_apps_steam_player_bans_steam_player_ownedgames_steam_player_stats_steam_player_summaries_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steam_player_rencentlyplaygames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_id', models.CharField(max_length=225)),
                ('appid', models.IntegerField()),
                ('name', models.CharField(max_length=225)),
                ('playtime_2weeks', models.IntegerField()),
                ('playtime_forever', models.IntegerField()),
                ('img_icon_url', models.CharField(max_length=225)),
                ('img_logo_url', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='steam_player_stats',
        ),
    ]
