# Generated by Django 2.0.2 on 2018-06-21 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0003_auto_20180621_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stats_id',
            new_name='re_id',
        ),
    ]
