# Generated by Django 2.0.2 on 2018-06-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0004_auto_20180621_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steam_news',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='steam_player_summaries',
            name='lastlogoff',
            field=models.DateTimeField(),
        ),
    ]
