# Generated by Django 2.0.2 on 2018-06-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0005_auto_20180621_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steam_news',
            name='date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='steam_player_summaries',
            name='lastlogoff',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='steam_player_summaries',
            name='timecreate',
            field=models.IntegerField(),
        ),
    ]
